### List all tickets
GET http://localhost:3001/api/ticket

### Get ticket by ticket_num  5OERR 3PU8N NMHCG
GET http://localhost:3001/api/ticket/Y5PTV

### Create a new ticket
POST http://localhost:3001/api/ticket
Content-Type: application/json

{
   "ticket_num": "FF99BX",
   "valid": true,
   "used": false
}
### Update Tickets to userd
POST http://localhost:3001/api/ticket/OG19YR
Content-Type: application/json

{
   "valid": true,
   "used": true
}

#### Requests to Orders
### List all orders
GET http://localhost:3001/api/orders

### Get order by order_number
GET http://localhost:3001/api/orders/ORD1726444313058

### Create a new order
POST http://localhost:3001/api/orders
Content-Type: application/json

{
  "order_number": "ORD1726445220560",
  "order_status": "pendente",
  "items": [
    {
      "item_name": "Refrigerante",
      "quantity": 1,
      "ticket_num": "Y5PTV"
    }
  ]
}

### Update a Order by id
PUT http://localhost:3001/api/orders/66e77319d2e60e22b57ea5bc
Content-Type: application/json

{
  "order_status":"cancelado"
}

### Delete a Order by id
DELETE http://localhost:3001/api/orders/66e77319d2e60e22b57ea5bc

